name: se347-user-svc
services:
#  kafka-console:
#    extends:
#      file: ../compose.yaml
#      service: kafka-console
#  kafka:
#    extends:
#      file: ../compose.yaml
#      service: kafka
#  zookeeper:
#    extends:
#      file: ../compose.yaml
#      service: zookeeper

  mongo-primary:
    profiles: ['dev','all']
    image: bitnami/mongodb:8.0.3-debian-12-r1
    container_name: mongo-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicaSetKey123
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-root}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER:-root}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-dev}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-dev}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-user-svc}
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=27017
    ports:
      - "27017:27017"
    networks: [dev]

  deps-cache:
    profiles:
      - deps-cache
    image : ${DOCKER_REGISTRY:-ghcr.io}/${IMAGE:-ngodat0103/se347-backend/deps-cache}:${IMAGE_VERSION:-dev-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: app-builder

  user-svc:
    profiles: ['all']
    mem_limit: 512m
    #cpus: 1
    image: ${DOCKER_REGISTRY:-ghcr.io}/${IMAGE:-ngodat0103/se347-backend/user-svc}:${IMAGE_VERSION:-dev-latest}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_MONGODB_HOST=mongo-primary
      - SPRING_DATA_MONGODB_USERNAME=${MONGODB_USERNAME:-dev}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGODB_PASSWORD:-dev}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE:-user-svc}
      - APP_VERSION=${IMAGE_VERSION:-dev-latest}
      - SPRING_PROFILES_ACTIVE=staging
      - SPRING_DATA_REDIS_HOST=redis
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-http://minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minio}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minio123}
    build:
      context: .
      dockerfile: Dockerfile
      cache_to:
        - "type=local,compression=gzip,compression-level=0,force-compression=true,mode=max,dest=/build-cache"
      cache_from:
        - "type=local,src=/build-cache"
      args:
        SERVER_PORT: 5000
        SERVICE_NAME: user-svc
        VERSION: ${TAG:-dev-latest}
    networks: [ dev ]
    healthcheck:
     test: ["CMD","curl","http://localhost:5000/actuator/health/readiness"]
     interval: 3s
     timeout: 3s
     retries: 3
    depends_on:
      mongo-primary:
        condition: service_started
    ports:
      - "5000:5000"
volumes:
  bitnami-mongodb:
    name: bitnami-mongodb
networks:
  dev:
    name: dev
    external: true
