name: se347-audit-svc
services:
  audit-svc:
    mem_limit: 512m
    #cpus: 1
    image: ${DOCKER_REGISTRY:-ghcr.io}/${IMAGE:-ngodat0103/se347-backend/audit-svc}:${IMAGE_VERSION:-dev-latest}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ELASTICSEARCH_URIS=http://elastic-search:9200
    build:
      context: .
      dockerfile: Dockerfile
      cache_to:
        - "type=local,compression=gzip,compression-level=0,force-compression=true,mode=max,dest=/build-cache"
      cache_from:
        - "type=local,src=/build-cache"
      args:
        SERVICE_NAME: audit-svc
        VERSION: ${TAG:-dev-latest}
    networks: [ dev ]
networks:
  dev:
    name: dev
    external: true
