spring:
  config:
    activate:
      on-profile: dev
  kafka:
    consumer:
      bootstrap-servers: [kafka-svc:9092]
      group-id: audit-svc
      auto-offset-reset: earliest
      enable-auto-commit: true
  main:
    web-application-type: none
  elasticsearch:
    uris: ["http://elasticsearch-svc:9200"]